### PR TITLE
tests

### PR DESCRIPTION
**Pull request by dominicrufa**
setting up a stage for testing

### CODE REVIEW

**Comment by dominicrufa** [comment]
https://github.com/choderalab/nn-endstates/blob/bbf7f9fafccc7b20f1dab029c5b9b90a73e21987/complete.py#L517; 
so, it is indeed true that there is a discrepancy between the force units in the ani-calculated force matrix and the mm-calculated force matrix; however, the matrices are `unit.Quantities` and are compatible. furthermore, https://github.com/choderalab/nn-endstates/blob/bbf7f9fafccc7b20f1dab029c5b9b90a73e21987/complete.py#L433 reconverts the calculated 'aggregate' force back to kJ/(mol nm) to be placed into the `integrator` as a 'modified force' so i am not convinced that there is a unit discrepancy here;

**Comment by dominicrufa** [comment]
there is a `tests.ipynb` containing a minimal `annealed_importance_sampling` run that anneals from MM->ani for a solvated benzene ring; perhaps this is the best place to begin looking to implement tests. 
potential tests that could be written: 
1. validate that the force matrix is being updated 'properly': https://github.com/choderalab/nn-endstates/blob/bbf7f9fafccc7b20f1dab029c5b9b90a73e21987/complete.py#L501
2. validate that the reduced energies are being computed properly: https://github.com/choderalab/nn-endstates/blob/bbf7f9fafccc7b20f1dab029c5b9b90a73e21987/complete.py#L491
3. the reduced energies are being converted to 'thermodynamic works' in accordance with the AIS procedure: https://github.com/choderalab/nn-endstates/blob/bbf7f9fafccc7b20f1dab029c5b9b90a73e21987/complete.py#L461

**Comment by maxentile** [comment]
Excellent -- thanks for all this, and for the orienting comments and pointers! Will take a close look Monday or Tuesday afternoon, aiming to implement the tests you describe and to see what else might need to be tested.

My aim in testing will be to help isolate whether there are possible issues in:
* thermodynamic cycle definition, by asserting that I get an end-state correction of 0 when the potential used for reweighting is no different from the MM potential used for sampling. (Also maybe asserting that a correction of 0 is obtained when things are offset by constants in a way that should cancel out.)
* units, by ensuring units are attached wherever possible, and by double-checking the encoded assumptions of when units are attached for the first time to something that comes out of un-unitted code.
* temperatures/pressures/etc, e.g. checking that the same temperature is being used to sample as is being used to compute reduced energies / reduced works.

**Comment by dominicrufa** [comment]
> thermodynamic cycle definition, by asserting that I get an end-state correction of 0 when the potential used for reweighting is no different from the MM potential used for sampling. (Also maybe asserting that a correction of 0 is obtained when things are offset by constants in a way that should cancel out.)

to be clear, the thermocycle is not implemented inside the `complete.py`; this script, which contains `annealed_importance_sampling` function to execute simply runs an annealing scheme between MM->ANI. postprocessing must be done to close the thermodynamic cycle

**Comment by maxentile** [comment]
>to be clear, the thermocycle is not implemented inside the complete.py; this script, which contains annealed_importance_sampling function to execute simply runs an annealing scheme between MM->ANI. postprocessing must be done to close the thermodynamic cycle

Ahh, could you please add a pointer to the code that implements the thermodynamic cycle? That's the main part I was hoping to review and test. If not, I'll mostly just double-check units / temperatures.

**Comment by dominicrufa** [comment]
> Ahh, could you please add a pointer to the code that implements the thermodynamic cycle? That's the main part I was hoping to review and test. If not, I'll mostly just double-check units / temperatures.

@maxentile , check out: https://github.com/choderalab/nn-endstates/pull/2/commits/b61f82a8ebc63829633ce7149d055a9228169f65
`thermocycle.ipynb` has my first attempt at making the endstate corrections

**Comment by maxentile** [comment]
Excellent, thanks!

**Comment by dominicrufa** [comment]
for the sake of covering all my bases, I have a test suite for all of the `coddiwomple` dependencies in `complete.py`; worth noting that `OMMLI` is a subclass of `openmmtools.integrators.ThermostatedIntegrator` so there are already tests for this and the `OMMBIP`, which is a subclass of `openmmtools.mcmc.BaseIntegratorMove`; the tests i wrote are here: https://github.com/dominicrufa/coddiwomple/blob/master/coddiwomple/tests/test_openmm.py.

**Pull request merged**
