### PR TITLE
Hydration

### PR DESCRIPTION
**Pull request by dominicrufa**
hydration MM->ANI corrections for 64 freesolv molecules

### CODE REVIEW

**Comment by jchodera** [comment]
@dominicrufa : We probably don't want to check data files into GitHub repos because they frequently have to be generated multiple times and cause the repo to grow to unwieldy sizes. Maybe we can keep the generator scripts in the repo and work out a better way to store revision-controlled data snapshots?

**Comment by jchodera** [comment]
We've been looking at [rucio](https://rucio.github.io/) for Folding@home dataset management, for example.

**Comment by dominicrufa** [comment]
> @dominicrufa : We probably don't want to check data files into GitHub repos because they frequently have to be generated multiple times and cause the repo to grow to unwieldy sizes. Maybe we can keep the generator scripts in the repo and work out a better way to store revision-controlled data snapshots?

redundant data stored on lilac have been deleted from the github repo

**Comment by jchodera** [comment]
You're probably already aware of this, but extra steps need to be taken to purge files beyond just `git rm` so they don't cause the repo to grow:
https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

**Pull request merged**
